server:
    port: 8082

logging:
    level:
        org.hibernate.SQL: DEBUG
        org.springframework.security: DEBUG

# use RibbonRoutingFilter instead of the SimpleHostRoutingFilter
zuul:
    routes:
        resources:
            serviceId: resources
            path: /resources/**
            sensitive-headers:
            stripPrefix: false

resources:
    ribbon:
        NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
        listOfServers: localhost:8081

spring:
    session:
        store-type: redis